spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bdooldb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8081

firebase:
  config:
    path: "/Users/hyunpark/Desktop/BDool/bdool-3cce6-dff899281525.json"
