spring:
  application:
    name: chat
  profiles:
    active: prod
  config:
    import: optional:configserver:211.188.50.29:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh