spring:
  application:
    name: member
  profiles:
    active: default
  config:
    import: optional:configserver:http://211.188.50.29:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh
