spring:
  datasource:
    url: jdbc:mysql://mysql:3306/bdooldb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 211.188.50.55 # Redis 컨테이너 이름
      port: 6379
      password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect  # MySQLDialect 설정

  mail:
    host: smtp.naver.com
    port: 587
    username: gusdn0413@naver.com
    password: SRPZSZZHSB39
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.naver.com
        debug: true


notification-service:
  url: http://notification-service:8082/api

channel-service:
  url: http://chat-service:8084/api