spring:
  mail:
    host: smtp.naver.com
    port: 587
    username: gusdn0413@naver.com
    password: SRPZSZZHSB39
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.naver.com
        debug: true

  datasource:
    url: jdbc:mysql://localhost:3306/bdooldb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  cache:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE