
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: kang1521/chat:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082 # 컨테이너가 사용하는 포트를 8081로 설정
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80            # 외부에서 접근할 포트
      targetPort: 8082    # 컨테이너의 포트를 8081로 설정
