spring:
  elasticsearch:
    uris: http://211.188.50.55:9200
    #uris: elasticsearch:9200
    username: elastic
    password: 6f=NrJX*JuDvuxD6wuux

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html