spring:
  application:
    name: workspace
  profiles:
    active: defalut
  config:
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh